### ISSUE TITLE
Support installation via Swift Package Manager

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2629]
The navigation SDK is currently available for installation via CocoaPods and Carthage, with some of the lighterweight dependencies (MapboxDirections, Turf, etc.) also available for installation via Swift Package Manager. SPM has a brighter long-term outlook than CocoaPods and Carthage, so we should try to support it as soon as it’s ready.

The navigation SDK can only support SPM once all its dependencies also support SPM, in particular:

* [ ] ~~Mapbox [map SDK]: mapbox/mapbox-gl-native#15241~~
* [x] MapboxMaps [map SDK]: #2794 #2808
* [x] MapboxAccounts: mapbox/mapbox-accounts-ios#1
* [x] MapboxCommon
* [x] MapboxDirections: mapbox/mapbox-directions-swift#362
* [x] MapboxMobileEvents: mapbox/mapbox-events-ios#250
* [x] MapboxNavigationNative
* [x] MapboxSpeech: mapbox/mapbox-speech-swift#25
* [x] Solar: ceeK/Solar#11 ceeK/Solar#50
* [x] Turf: mapbox/turf-swift#30

The following dependencies are also needed for the SPM build to be testable:

* [ ] [Cedar](https://github.com/cedarbdd/cedar/)
* [x] [Quick](https://github.com/Quick/Quick/)
* [x] [Nimble](https://github.com/Quick/Nimble/)
* [x] [OHHTTPStubs](https://github.com/AliSoftware/OHHTTPStubs/)
* [ ] [FBSnapshotTestCase](https://github.com/facebookarchive/ios-snapshot-test-case/)
* [ ] [SnappyShrimp](https://github.com/AndriiDoroshko/SnappyShrimp/)

/cc @mapbox/navigation-ios @frederoni

**Comment by frederoni** [comment]
SPM support in MapboxMobileEvents https://github.com/mapbox/mapbox-events-ios/pull/250

**Comment by 1ec5** [comment]
The map SDK, MapboxCommon, and MapboxNavigationNative all require .netrc for downloading, so the changes in apple/swift-package-manager#2833 apple/swift-tools-support-core#88 will help to unblock SPM support in the navigation SDK.

**Comment by 1ec5** [comment]
mapbox/mapbox-directions-swift#494 tracks a major gap in code coverage when testing MapboxDirections with Swift Package Manager.

**Comment by MarcoCarnevali** [comment]
@1ec5 are there any news about this?

**Comment by FestiFete** [comment]
Didn't see any updates in v1.2.0 change logs, any news about it?

**Comment by 1ec5** [comment]
MapboxCoreNavigation support for SPM is progressing in mapbox/mapbox-navigation-ios#2771. MapboxNavigation support for SPM is blocked by ceeK/Solar#11 and mapbox/mapbox-gl-native#15241. Realistically speaking, MapboxNavigation support for SPM is blocked by upgrading to [map SDK v10](https://github.com/mapbox/mapbox-maps-ios/) because that’s the focus of map SDK development nowadays.

**Comment by 1ec5** [comment]
The issue description above originally focused on framework dependencies, because the idea was to at least stand up SPM as an alternative build environment as part of a transition towards SPM. However, SPM is now important enough that we need to make sure the test targets also build under SPM. Of the six (six!) testing frameworks this repository depends on, only three currently support SPM. Cedar, FBSnapshotTestCase, and SnappyShrimp not only lack support for SPM but are also unmaintained. We can eliminate MapboxCoreNavigationTests’ dependency on Cedar, but for MapboxNavigationTests to fully support SPM, we’ll need to substantially streamline our testing code.

**Comment by 1ec5** [comment]
As of #2771, you can install MapboxCoreNavigation using SPM. Anecdotally, using SPM saves quite a bit of time compared to Carthage if you only need MapboxCoreNavigation. I’m leaving this issue open to track installing MapboxNavigation using SPM, since that’s what most developers would be interested in. We also need to increase code coverage under SPM to where it is with Carthage: #2792.

**Comment by 1ec5** [comment]
The documentation script also needs to use SPM instead of Carthage to discover the most recent MapboxDirections docset to link to:

https://github.com/mapbox/mapbox-navigation-ios/blob/2bb7f9766226600e47ba91c06ebab40e173d0c77/scripts/document.sh#L30-L31

**Comment by 1ec5** [comment]
As of #2808 and v2.0.0-alpha.1, MapboxNavigation also supports SPM. We’re still tracking some significant tail work:

* MapboxMaps is currently depending on a binary alpha release of Turf, but it needs to depend on a source distribution of Turf going forward.
* MapboxCoreNavigationTests and TestHelper depend on MapboxNavigation: #2820.
* MapboxNavigationTests depends on unmaintained testing frameworks that don’t support SPM: #2791.
