### ISSUE TITLE
Binary dependencies are unavailable in XCFramework format

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-navigation-ios#2672]
The linker error in mapbox/mapbox-navigation-ios#2665 (specific to CocoaPods and Xcode 12) forced us to implement a workaround in #2667 that sets the `EXCLUDED_ARCHS` build setting not only in the MapboxCoreNavigation and MapboxNavigation framework targets but also in the developer’s application target. That gets us past the immediate issue and allows us to release v1.0.0, but it sets us up for incompatibility down the line. If another pod employs the same workaround, an application would be unable to install both pods at the same time.

The better fix is to rebuild all three binary dependencies with Xcode 12 and distribute them as XCFrameworks. Once that build is available, we can remove the workaround from the podspecs:

* [ ] Mapbox [map SDK]: mapbox/mapbox-gl-native-ios#171 mapbox/mapbox-maps-ios#48
* [x] MapboxAccounts mapbox/mapbox-accounts-ios-internal#36 - released in v2.3.1
* [x] MapboxNavigationNative mapbox/mapbox-navigation-native#2031 - released in v28.1.0

Migrating these dependencies to XCFrameworks will also allow developers to use Carthage directly without a workaround script once Carthage/Carthage#3019 is released.

/cc @mapbox/navigation-ios

**Comment by 1ec5** [comment]
This is what it looks like when multiple pods set `EXCLUDED_ARCHS` to different values:

```
[!] Can't merge user_target_xcconfig for pod targets: ["Mapbox-iOS-SDK", "MapboxCoreNavigation"]. Singular build setting EXCLUDED_ARCHS[sdk=iphonesimulator*] has different values.
```

It’s only a warning, but that might be because both pods happen to specify interchangeable values.

**Comment by 1ec5** [comment]
> It’s only a warning, but that might be because both pods happen to specify interchangeable values.

It’s a warning when integrating the pod into a real project, but when linting the podspec or pushing it to CocoaPods trunk, it results in an error: #2739.

**Comment by 1ec5** [comment]
Now that MapboxAccounts v2.3.1 and MapboxNavigationNative v28.1.0 are available, it should be possible to remove the arm64 workaround from MapboxCoreNavigation.podspec and apply the `user_target_xcconfig` override to just MapboxNavigation.podspec:

https://github.com/mapbox/mapbox-navigation-ios/blob/49e4bfbc52c18d24babe3740f1a33f5623c85aae/MapboxCoreNavigation.podspec#L51-L59 https://github.com/mapbox/mapbox-navigation-ios/blob/49e4bfbc52c18d24babe3740f1a33f5623c85aae/MapboxNavigation.podspec#L54-L58

**Comment by 1ec5** [comment]
All of MapboxCoreNavigation’s binary dependencies are now available as XCFrameworks, so MapboxCoreNavigation can now be built for simulators on M1-based Macs. For CocoaPods users, #2770 (available in v1.2.0-beta.1) streamlined the MapboxCoreNavigation podspec to no longer override the `EXCLUDED_ARCHS` build setting, which will improve compatibility with non-Mapbox frameworks. For Carthage users, Carthage/Carthage#3019 has landed but hasn’t been released yet, so you’ll need to [build Carthage from source](https://github.com/Carthage/Carthage/tree/cdc5eaa0cf8091f9f42ee49af8785714b894ab57#installing-carthage) and [build and embed](https://github.com/Carthage/Carthage/tree/cdc5eaa0cf8091f9f42ee49af8785714b894ab57#building-platform-independent-xcframeworks-xcode-12-and-above) MapboxAccounts.xcframework, MapboxCommon.xcframework, and MapboxNavigationNative.xcframework into your application target.

MapboxNavigation additionally depends on the map SDK, which still isn’t available as an XCFramework: mapbox/mapbox-gl-native-ios#171. For CocoaPods users, the podspec still overrides the `EXCLUDED_ARCHS` build setting, which may cause CocoaPods errors like #2739 when using the navigation SDK alongside some non-Mapbox pods. For Carthage users, the [workaround script](https://github.com/Carthage/Carthage/issues/3019#issuecomment-665136323) is still required for now.

**Comment by 1ec5** [comment]
As of #2771, Carthage users who only need MapboxCoreNavigation can now use SPM instead of Carthage to install that library with support for Apple Silicon. [Here are some instructions](https://github.com/mapbox/mapbox-navigation-ios/blob/2bb7f9766226600e47ba91c06ebab40e173d0c77/custom-navigation.md#using-swift-package-manager), but you’ll need to use `.branch("main")` for now until v1.3.0 comes out.

**Comment by 1ec5** [comment]
As of #2808 and v2.0.0-alpha.1, both MapboxCoreNavigation and MapboxNavigation support SPM. SPM actually defaults to static linking, which is even better in some ways than XCFramework. #2810 tracks removing the Carthage workaround in favor of relying on Carthage’s built-in XCFramework support.

Part of the arm64 workaround is still in one of the CocoaPods podspecs. Leaving this issue open to track removing that workaround, which is blocked by mapbox/mapbox-gl-native-ios#171 in the v1._x_ branch and mapbox/mapbox-maps-ios#48 in the v2._x_ branch.

**Comment by truburt** [comment]
@1ec5 , is it for 1.3.0 or 2.0 now?

**Comment by 1ec5** [comment]
Fixed in mapbox/mapbox-navigation-ios#2808 for v2.0.0-alpha.1.
